### ISSUE TITLE
Browser is flagging hotfix version as containing a virus when trying to download

### ISSUE THREAD

**Issue by itompkins** [soda3x/ArmaReforgerServerTool#101]
Virus scanner is flagging the exe as containing "Trojan:Win32/Wacatac.B!ml" when I attempt to download the file.

**Comment by NASYROV777** [comment]
> При попытке загрузить файл антивирусная программа помечает его как содержащий «Trojan:Win32/Wacatac.B!ml».

У меня все работает и проблем таких не было!

**Comment by soda3x** [comment]
I can assure you it isn't, I will send a VirusTotal result!

**Comment by itompkins** [comment]
understood. It was just weird. Thanks for the prompt response
