### ISSUE TITLE
The mission header is malformed

### ISSUE THREAD

**Issue by JoshWalki** [soda3x/ArmaReforgerServerTool#105]
When attempting to save mission header, the below error shows.
Regardless of syntax used, the error persists.

![image](https://github.com/user-attachments/assets/068410d6-26e5-4e20-8794-b76b6eed720d)

`"serverMessageHeaderImage": "{***}\images\***.edds"`
or 
`{"serverMessageHeaderImage": "{***}\images\***.edds"}`

**Comment by soda3x** [comment]
it's likely the curly braces in there, might need to escape them with `\` `"\{***\}\ . . .`

**Comment by soda3x** [comment]
try and use `/` instead of `\` for the path: `{"serverMessageHeaderImage": "\{***\}/images/***.edds"}`

**Comment by JoshWalki** [comment]
Thank you for the suggestion but I've tried `{"serverMessageHeaderImage": "\{***\}/images/***.edds"}` and the same error still occurs
