### ISSUE TITLE
Implement config params from 0.9.9.x patches

### ISSUE THREAD

**Issue by soda3x** [soda3x/ArmaReforgerServerTool#14]
The following should be implemented for the 0.7.x update for the tool to bring up to date with the latest 0.9.9.x patches:

* `admins` (Parent: `game`) - a list of server admins that can use `#login` without a password
* `slotReservationTimeout` (Parent: `gameProperties`) - Number between 5 and 300 (both inclusive, default 60) determining how long the server slot should be reserved for a player who disconnects
* ~~Update `serverMinGrassDistance` to not allow values less than 50 as those values are no longer valid (`v0.6.x` workaround is to set a higher grass value to get the server running)~~ (resolved in `v0.7.0`)
* ~~`operating` is no longer valid in the configuration, investigate where parameters under that should now live~~ (resolved in `v0.6.2`)
* ~~Remove deprecated `gameNumber` field~~ (resolved in `v0.6.2`)
* ~~Rename `supportedGameClientTypes` to the new name `supportedPlatforms`~~ (resolved in `v0.6.2`)

Note: Strikethrough indicates that that item has been resolved

**Comment by soda3x** [comment]
Seems that `operating` used to live under `gameProperties` but is now a root object

**Comment by soda3x** [comment]
`operating` has always been in root according to a dev. The latest patch adds validation to the config so those parameters actually never worked in this tool 😲

**Comment by PulsarNeutronStar** [comment]
the usual question, i know. but is there an ETA for the fix?

Current version is borked due to `gameNumber`, at least for me that is.

**Comment by soda3x** [comment]
part 1 of this fix will be released today

**Comment by soda3x** [comment]
@PulsarNeutronStar v0.6.2 is now released

**Comment by soda3x** [comment]
Fixed Server Min Grass Distance in `v0.7.0` of which the launch is imminent

**Comment by soda3x** [comment]
All remaining parameters have been implemented in `v0.8`
