### ISSUE TITLE
Add Mission Header Capabilities to Configuration

### ISSUE THREAD

**Issue by trapperbrown** [soda3x/ArmaReforgerServerTool#18]
In some cases, it might be useful to add mission header parameters in the autogenerated "server.json."

For example, for a certain mod to work, I will need to add the following lines to "server.json" under "gameProperties":

			"missionHeader": {
				"DPL_DiscordChannelId": "CUSTOM",
				"DPL_DiscordChannelName": "CUSTOM",
				"DPL_DiscordMessageTitle": "CUSTOM",
				"DPL_ServerIp": "CUSTOM"
			}

Example including gameProperties:

		"gameProperties": {
			"serverMaxViewDistance": 2200,
			"serverMinGrassDistance": 50,
			"networkViewDistance": 650,
			"disableThirdPerson": false,
			"fastValidation": true,
			"battlEye": true,
			"VONDisableUI": false,
			"VONDisableDirectSpeechUI": false,
			"missionHeader": {
				"DPL_DiscordChannelId": "CUSTOM",
				"DPL_DiscordChannelName": "CUSTOM",
				"DPL_DiscordMessageTitle": "CUSTOM",
				"DPL_ServerIp": "CUSTOM"
			}
		},

**Comment by soda3x** [comment]
Will look into adding this in the next update

**Comment by soda3x** [comment]
Resolved in `v0.7`
