### ISSUE TITLE
Server Crash Detection

### ISSUE THREAD

**Issue by trapperbrown** [soda3x/ArmaReforgerServerTool#19]
Would it be possible to add a mechanism that detects a server crash and then automatically attempts to reboot? 

Sometimes in Arma Reforger, as you know, nothing is wrong with the mods/code, but it can crash when too many AI or other things like that are presented into the game and this feature would be fantastic.

Thanks!

**Comment by soda3x** [comment]
I'll look into it!

**Comment by soda3x** [comment]
Added in v0.9.1
