### ISSUE TITLE
Implement config params from V1.0 patch

### ISSUE THREAD

**Issue by soda3x** [soda3x/ArmaReforgerServerTool#21]
Implement the following parameters:
* ~~`VONCanTransmitCrossFaction`~~ (implemented in `v0.8`)
* ~~`disableNavmeshStreaming`~~ (implemented in `v0.8`)
* `rcon`

Note: strikethrough indicates implemented

**Comment by FabioPro84** [comment]
Hello @soda3x , I tried using the -loadSessionSave parameter to achieve some sort of persistence after restarting the hosting server. I would like to use the same parameter with your tool on my dedicated server. Is it possible for you to add this feature?

**Comment by soda3x** [comment]
> Hello @soda3x , I tried using the -loadSessionSave parameter to achieve some sort of persistence after restarting the hosting server. I would like to use the same parameter with your tool on my dedicated server. Is it possible for you to add this feature?

Yep, I'll add that too!

**Comment by soda3x** [comment]
> Hello @soda3x , is it possible to add the slotReservationTimeout part? Do you know how long it will take for you to make this change?

Hi, this should be easy to implement, I can get it done today most likely :)

**Comment by soda3x** [comment]
All of these except rcon have now been implemented in `v0.8`. Rcon to follow.

**Comment by Prodigyfly** [comment]
Hi @soda3x, I know I'm asking a lot and if you want to curse me out, I'll allow it 🤣. Is it possible to have a guide where you explain every parameter that can be set through your tool? 
Many of these things are unknown to me and if they can be useful for the server, I wouldn't mind being able to configure them correctly.
Thank you for your work and for the promptness in execution.

**Comment by soda3x** [comment]
> Hi @soda3x, I know I'm asking a lot and if you want to curse me out, I'll allow it 🤣. Is it possible to have a guide where you explain every parameter that can be set through your tool? 
> Many of these things are unknown to me and if they can be useful for the server, I wouldn't mind being able to configure them correctly.
> Thank you for your work and for the promptness in execution.

Hey! For the time being, the best place to learn about these parameters is probably [the Arma Reforger server hosting page](https://community.bistudio.com/wiki/Arma_Reforger:Server_Config). I'll try and add some more tooltips to controls in the future.

**Comment by soda3x** [comment]
> Hi @soda3x, I know I'm asking a lot and if you want to curse me out, I'll allow it 🤣. Is it possible to have a guide where you explain every parameter that can be set through your tool? Many of these things are unknown to me and if they can be useful for the server, I wouldn't mind being able to configure them correctly. Thank you for your work and for the promptness in execution.

Hey @Prodigyfly, latest version contains tooltips for each parameter! Hope this makes this easier :)

**Comment by soda3x** [comment]
Rcon implemented in `v0.9.0`
