### ISSUE TITLE
Senario ID User Input

### ISSUE THREAD

**Issue by billt316** [soda3x/ArmaReforgerServerTool#22]
First off, a huge THANK YOU! As someone that does not have much experience with coding or reading documentation when it comes to dedicated servers I really needed this tool to get my server going properly. After many painful attempts at making start up files and config files this did the trick. I think this tool is extremely useful for people like me, I doubt I'm alone. Would you be willing and is it possible to add the ability to select custom scenarios from the drop down menu or allow users to input the right text to point to a mission wrapped in a mod? I'd really like to try conflict with the addition of RHS but it seem you need to place a scenario ID in the config file to get it to operate correctly.

**Comment by soda3x** [comment]
Hiya! Glad you like the tool, I'm in the process of adding this. Hit a few roadblocks but stay tuned!

**Comment by soda3x** [comment]
Tracking this in #8

**Comment by soda3x** [comment]
Resolved in `v0.7`
