### ISSUE TITLE
Does not save game progress

### ISSUE THREAD

**Issue by AlessandroSInoue** [soda3x/ArmaReforgerServerTool#28]
It's just saving loadout.
I'm running the server on my computer at home, and After stopping and shutting down the server, the game's progress returns to zero.
I'm using the latest version 0.7.1.

**Comment by soda3x** [comment]
Yep, I have not implemented that yet. A later version will support this, please stay tuned!

**Comment by jez-bo** [comment]
> It's just saving loadout. I'm running the server on my computer at home, and After stopping and shutting down the server, the game's progress returns to zero. I'm using the latest version 0.7.1.

You need to find the .bat file that executes the sever startup, edit the file in text editor or any interpreter, add this function -loadSessionSave

I can't find that particular bat file but that's what I add to my normal steam CMD server and it will save your server progress

**Comment by Prodigyfly** [comment]
@soda3x Sorry to bother you, do you have any idea when you will release the new update with the addition of progress saving? My players are insulting me every time I have to restart the server 😜.

**Comment by soda3x** [comment]
> @soda3x Sorry to bother you, do you have any idea when you will release the new update with the addition of progress saving? My players are insulting me every time I have to restart the server 😜.

Hiya! I am planning on fully rewriting this app so that it may be easier for me to implement new features as they come. Obviously this will take some time, however, I'll look into it and see what is required to implement the feature. I'll reply again when I have investigated :)

Please apologise to your players on my behalf!

**Comment by Prodigyfly** [comment]
@soda3x Thank you for your prompt response. Is there anything that needs to be enabled on the console?

**Comment by soda3x** [comment]
> Hello @soda3x .Thank you for the promptness of the development. Sorry to bother you. Where does it save the files for persistence ? I'd like to be able to insert the correct path so that if I change the mission, I can load the correct progress

I'm not 100% sure right now, I'd assume it's where the server files are located.

**Comment by jmenard71** [comment]
Hey thanks a lot for that. I just stop my server (with 0.7.1) updated the tool to 0.7.2 and when I restarted my server the saved game was there! I used default path (empty field)

**Comment by soda3x** [comment]
> Hey thanks a lot for that. I just stop my server (with 0.7.1) updated the tool to 0.7.2 and when I restarted my server the saved game was there! I used default path (empty field)

Perfect!
