### ISSUE TITLE
cant launch the app

### ISSUE THREAD

**Issue by xdxd123** [soda3x/ArmaReforgerServerTool#3]
The app wont launch

**Comment by soda3x** [comment]
Any more information?

**Comment by xdxd123** [comment]
I simply click to open and it does nothing. Not even through the listed search result to launch it.

![image](https://user-images.githubusercontent.com/20619481/173067344-8c58b003-8c8f-4f4e-8fc1-850c47e5789c.png)

![image](https://user-images.githubusercontent.com/20619481/173067379-7086b5ea-8d88-4637-a793-843c98843518.png)

**Comment by xdxd123** [comment]
Also I don't know where any logs would be.

**Comment by xdxd123** [comment]
My discord is jangofett#1950 if you have discord and I can screenshare.

**Comment by soda3x** [comment]
Do you have dotnet 6 installed? It is required.

**Comment by xdxd123** [comment]
Nope, that fixed it. Thanks!

**Comment by soda3x** [comment]
Awesome! I'll update the README so it's clear what's required for it to run
