### ISSUE TITLE
High Ping Unable to join own hosted server.

### ISSUE THREAD

**Issue by kakaheadboi** [soda3x/ArmaReforgerServerTool#33]
Hey team! tool has worked good and I see my server in the server list.

However the ping shown is 999+. and i am unable to join unfortunately.

Any ideas? 

Andy

**Comment by kakaheadboi** [comment]
I should mention my ISP speed is 500mb down 100 up if that accounts for anything.

**Comment by soda3x** [comment]
Hi, I haven't had this issue. I will investigate!

**Comment by soda3x** [comment]
Try running the stable for a while and see if it stabilises

**Comment by soda3x** [comment]
If you have any friends who are playing, ask them if they can join and what the ping is

**Comment by kakaheadboi** [comment]
My apologies!! I made an idiot and did not set the public ip correctly. 

Ran perfect for hours and had a great time! 

Thank you muchly for the tool!
