### ISSUE TITLE
ping 999 end error message

### ISSUE THREAD

**Issue by BlackburnUTG** [soda3x/ArmaReforgerServerTool#37]
Me, and my 2 friends tried to host/connect to each other - we didn't manage to do that.
we did forward ports 2001 17777 and 19999 - it didn't helped
error message:
group=1 REPLICATION reason=3 CONNECTION FAILURE

---
I tried search the error in arma discord. and found this:
 

> {"bindAddress": "",
    "bindPort": 2001,
    "publicAddress": "XXX.XXX.XXX.XXX",
    "publicPort": 2001,
    "game": { 
try adding this before "game", just use your servers pouiblic addres where i put xxx.xxx.xxx.xxx
worked for me

I didn't tried to this yet, because IDK how to do that in your program

**Comment by soda3x** [comment]
remove public address and bind address and replace with 0.0.0.0 and see what happens, the config file generated by the program should be valid so long as the IP and ports are valid. Make sure you're not running multiple servers on the same machine. let me know how that goes.

**Comment by BlackburnUTG** [comment]
I tested it more;
- if bindAddress and publicAddress are 0.0.0.0 : then ping is 999 and erorr group=1 REPLICATION reason=3 CONNECTION FAILURE
- if bindAddress and publicAddress are empty, or with my real ip, then ping is ok, but error "group=1 REPLICATION reason=3 CONNECTION FAILURE" is still here. Cant connect

**Comment by soda3x** [comment]
Interesting, maybe check firewall settings? make sure your ISP doesn't have you on CGNAT also.

**Comment by oIBRAHIMo1** [comment]
Hey @BlackburnUTG have you found any solution ? i have the same issue, this is not something specific to soda3x ArmaReforgerTool but more of networking issue

**Comment by BlackburnUTG** [comment]
> Hey @BlackburnUTG have you found any solution ? i have the same issue, this is not something specific to soda3x ArmaReforgerTool but more of networking issue

yeah, I had this issue even when I did self hosting. 
I think I fixed this...
I figured out that my friends from Ukraine cant connect to me (I am from Russia), because of the war and politics. But with VPN we can.
And dont forget to open ports 2001 17777 and 19999

**Comment by oIBRAHIMo1** [comment]
> > Hey @BlackburnUTG have you found any solution ? i have the same issue, this is not something specific to soda3x ArmaReforgerTool but more of networking issue
> 
> yeah, I had this issue even when I did self hosting. I think I fixed this... I figured out that my friends from Ukraine cant connect to me (I am from Russia), because of the war and politics. But with VPN we can. And dont forget to open ports 2001 17777 and 19999

I started using VPN too i port forwarded from the VPN and worked , it looks like is something on Bohemia side

**Comment by PulsarNeutronStar** [comment]
> I tested it more;
> 
>     * if bindAddress and publicAddress are 0.0.0.0 : then ping is 999 and erorr group=1 REPLICATION reason=3 CONNECTION FAILURE
> 
>     * if bindAddress and publicAddress are empty, or with my real ip, then ping is ok, but error "group=1 REPLICATION reason=3 CONNECTION FAILURE" is still here. Cant connect

can confirm, removing 0.0.0.0 from bind and public it resolved the 999 ping issue, but i still get the same group=1 reason=3 error. Trying to connect from Germany to a Germany Hosted Dedcated Server :harold:

**Comment by PulsarNeutronStar** [comment]
Got it to work:
bind IP: empty
public IP: actual public IP

**Comment by soda3x** [comment]
Glad you solved it

**Comment by FATTYTRACER** [comment]
i did everything that has been done but nothing works. 
i tried:
bind ip: empty
public ip: 0.0.0.0
-
and then i tried:
bind ip: 0.0.0.0
public ip: empty
-
then i treid to put:
bind ip: 0.0.0.0
public ip: my own ip
-
then i tried:
bind ip: empty
public ip: my own ip
-
i have port forwarded all ports mentioned and even more from the Bohemia website. do you think it has to do with the  ISP doesn't have me on CGNAT? keep in mind i live in the UK and same thing for my friend who is trying to join.

ive also added new inbound rules to the firewall with the same ports. (i dont have any antivirus software's installed)

please any suggestions?

**Comment by kakaheadboi** [comment]
Hey all!! I’m having the same issue! Has persisted for three or four days now. I was hosting a server fine for myself and two friends but have been running into the same “replication, connection failure” issue. 

Server shows up with a good ping in server list but does not allow anyone to join. Have had bind address set to 0.0.0.0 aswell, using the same settings that had been working before. 

Any help is greatly appreciated! I have also deleted and reset my server files
