### ISSUE TITLE
Add Mod

### ISSUE THREAD

**Issue by Spitzi0815** [soda3x/ArmaReforgerServerTool#40]
Hallo,
how to add mod?
I klick add mod, paste the Name and ID from Mod and then? I can only the the Window close with ALT+F4.
Please help.

**Comment by oIBRAHIMo1** [comment]
"I klick add mod, paste the Name and ID from Mod and then" That how it is, then you enable it for your server pass it from left table = disable to right table = enable

**Comment by Spitzi0815** [comment]
The left table has no Mods. I will  add Mods. How to can i Mods add to left Table?
The Button Add-Mod klick, paste the Name and ID from Mod and then? I can only the the Window close with ALT+F4

**Comment by soda3x** [comment]
There's a confirmation button on the add mod dialog, that will add the mod to the left column

**Comment by Spitzi0815** [comment]
Ok, thanks all,

i have change the HighDPI-Settings  under Kompalität for this nice Tool and now i can see the Button :-)
