### ISSUE TITLE
I CANT JOIN THE SERVER THAT I AM CREATING (urgent)

### ISSUE THREAD

**Issue by FATTYTRACER** [soda3x/ArmaReforgerServerTool#41]
HELLO, 

i have followed all the steps step by step from the tutorial you provided, i even watched a video on YouTube detailing everything single step on how to create the server on using the arma reforger dedicated server tool. i even added port forwarding to my WiFi router (2001, 17777, 2302, and all the ports asked to put on the Bohemia website) and added rules on my firewall (as ive been advised by that guy on YouTube after facing issues. ive tried using a different internet with a different router and internet provider. i keep getting the same error message after joining "error group=1 'REPLICATION', reason=3 'CONNECTION_FAILURE". 

main point is that im not able to join the server, and neither can my friends.

**Comment by PulsarNeutronStar** [comment]
checkout #37

**Comment by FATTYTRACER** [comment]
i have tried all the solutions there but i just have a question about how should i set it up with a vpn, idk how to do that if there is a way for you to tell me how to do it step by step?

**Comment by soda3x** [comment]
It shouldn't require a VPN...

**Comment by FATTYTRACER** [comment]
what do u think i should do?

**Comment by FATTYTRACER** [comment]
is there a way we can speak on discord and you can help me with this while i share my screen?

**Comment by kakaheadboi** [comment]
Having the exact same issue @FATTYTRACER

I had the server running great with this tool before the last two Arma game updates. Now I get the same error, although I’m running the same configs I did when it was running great. So I’m sort of at a loss.


I feel it must be something Bohemia side that is messing with the way the server tool works. 

I have re installed the server tool, along with reinstalled the runtime.

**Comment by soda3x** [comment]
I am investigating.

**Comment by soda3x** [comment]
Closing and will track in #44
