### ISSUE TITLE
I can't create a server

### ISSUE THREAD

**Issue by Vuscin** [soda3x/ArmaReforgerServerTool#42]
I can get to the point that the server is in the server lists, with a ping of 30. When I attempt to join the server I get connection refused.

**Comment by PulsarNeutronStar** [comment]
whats the error message?

**Comment by kakaheadboi** [comment]
Having had the same issue for three to four days now. Am using the same server load that I had running fine a couple weeks ago. 

Bind ip had always been 0.0.0.0 and my public ip has been my correct IP aswell. Have deleted and made a new server file aswell. 

My friends and I can see the server in the list with good ping, however we all get the same “replication….. connection failure” message

**Comment by soda3x** [comment]
I am investigating.

**Comment by soda3x** [comment]
Closing and will track in #44
