### ISSUE TITLE
(Group 1 Replication Reason 3 Connection Failure)

### ISSUE THREAD

**Issue by kakaheadboi** [soda3x/ArmaReforgerServerTool#43]
Howdy! Have been loving the server tool, it’s a hit. 

However I am running into what seems to be an arising issue?! 

My friends and I can see my server show up in the list, with good ping. We join, it loade for a minute and then gives us the error message shown in the the title. 

I am using the exact same config/save I had used when the server was letting myself and friends connect with ease! So I’m assuming this is a Bohemia side issue? 

Cheers!
Andy

**Comment by soda3x** [comment]
I am seeing an alarming amount of these issues. My guess is it's on Bohemias side. They rolled out a new patch in the last few days so that may have changed some things. I am investigating. If this is a common issue, I may start up a FAQ.

**Comment by soda3x** [comment]
Closing and will track in #44
