### ISSUE TITLE
Combat Ops Everon Save And Load Not working?

### ISSUE THREAD

**Issue by Maddymoo98** [soda3x/ArmaReforgerServerTool#45]
Does not seem to be Working?

**Comment by soda3x** [comment]
Will investigate

**Comment by soda3x** [comment]
![image](https://github.com/soda3x/ArmaReforgerServerTool/assets/25409948/3d120411-0b39-4c41-ab11-ea62d1988224)
Ensure you have this selected

**Comment by Maddymoo98** [comment]
Yes I did Do I just press it Once Then from that time on its good? I Did it both times and I noticed it wasnt loading my save? :(

**Comment by Maddymoo98** [comment]
Where does it   pull the save from? Im sorry if i seem a bit dumb

**Comment by soda3x** [comment]
> Where does it pull the save from? Im sorry if i seem a bit dumb

You don't at all, its a bit strange. It's stored within the server files. That field is used to specify a specific save, useful for if you have multiple campaigns / missions going at once. The field assumes all the saves are in the same spot so its not like you pass it a path like `C:/Users/Me/My Saves/my_save.json` it wants `my_save.json`. If you leave the field empty, it just loads the last save which is why for the time being, i suggest leaving that field empty.

**Comment by gate1310** [comment]
> > Where does it pull the save from? Im sorry if i seem a bit dumb
> 
> You don't at all, its a bit strange. It's stored within the server files. That field is used to specify a specific save, useful for if you have multiple campaigns / missions going at once. The field assumes all the saves are in the same spot so its not like you pass it a path like `C:/Users/Me/My Saves/my_save.json` it wants `my_save.json`. If you leave the field empty, it just loads the last save which is why for the time being, i suggest leaving that field empty.

I followed these steps, it still did not load my CO: Everon session back to the state I left it at. 

I tested it by launching a fresh CO: Everon scenario, drove to the nearest hideout, unlocked it, waited a while to be sure, then logged out, then stopped the server and restarted it. Fresh install.

**Comment by soda3x** [comment]
Ok I'll investigate further. A new patch for Reforger recently dropped so it might have changed some things.

**Comment by Maddymoo98** [comment]
Is there an Update on this?

**Comment by soda3x** [comment]
I can confirm that the tool does indeed include `-loadSessionSave` when it's ticked, are you sure the mod / scenario / mission you're using supports saving?

**Comment by gate1310** [comment]
The saving isn't working for the game mode, Combat Ops: Everon. Thats what this thread was opened about.

**Comment by soda3x** [comment]
Hey guys, I have some _mixed_ news regarding this.

So I can confirm its not the dedicated server tool causing this, but rather the Combat Ops mission.

https://forums.bohemia.net/forums/topic/240049-linux-dedicated-server-cant-save-scenario-progression/

Above is one of a few reports I can find of this occurring.

I will be fleshing out the session save loading features in the tool pretty soon too so stay tuned for that. Going to close out this issue as this is not an issue with the tool. Sorry I can't come with good news.
