### ISSUE TITLE
Crash after selectioning scenario

### ISSUE THREAD

**Issue by sfrechette88** [soda3x/ArmaReforgerServerTool#51]
I setup the server, run it, and all work perfectly.

After that, I stop the server, change Scenario, and the app crash. I reopen it, reload setting from file (for modlist and server settings) I right after I selected a scenario, the app crash.

**Comment by soda3x** [comment]
If so, please attach here

**Comment by sfrechette88** [comment]
Simply : 
![image](https://github.com/soda3x/ArmaReforgerServerTool/assets/60042459/fbfae94b-883a-4cc6-850f-2c55050a3d96)

**Comment by soda3x** [comment]
That's interesting, any chance you could join the Discord and record a video of what exactly you do? Would help a lot

**Comment by oIBRAHIMo1** [comment]
This does happens to me to, i just been ignoring it. Happens when you open to select a scenario, so my workaround is to quickly select a scenario and save it to a file so when it crash and i open it back the scenario is already selected.

**Comment by soda3x** [comment]
if either of you could join the discord and record a video of this behaviour it would be great :) I want to fix it!

**Comment by littleAndyy** [comment]
having the same issue here, just instantly closes down not long after selecting scenario

**Comment by littleAndyy** [comment]
having same issue, closes down instantly after a little bit of time

**Comment by soda3x** [comment]
Fixed as of `v0.8.3.2`
