### ISSUE TITLE
config.Json

### ISSUE THREAD

**Issue by Bandesss** [soda3x/ArmaReforgerServerTool#57]
Where can I find the Server.Json? because I got the error Loading dedicated server config.
2024-05-18 19:32:58: BACKEND(S): JSON parse error: Invalid encoding in string. (Line: 234 | Char: 37)
Thx for the Programm

**Comment by soda3x** [comment]
As long as the program is running, you can find `server.json` in the folder where your Reforger Server Files are located

**Comment by Bandesss** [comment]
Many thx 
Closed
