### ISSUE TITLE
Arma Reforger update 1.2.0 broke the Tool

### ISSUE THREAD

**Issue by Darojax** [soda3x/ArmaReforgerServerTool#60]
The "disableNavmeshStreaming" value in the server.json has changed from a boolean to an array with update 1.2.0, so will only require a minor change to make it work again I suspect.

![image](https://github.com/soda3x/ArmaReforgerServerTool/assets/110496226/6204655b-c8de-4601-be80-eedd7b7e44c6)

**Comment by soda3x** [comment]
No worries, will look into it

**Comment by Barros1776** [comment]
cant wait for an update. thanks for this tool, bro

**Comment by soda3x** [comment]
See `v0.8.3.1` release for the hotfix if you don't rely on the parameter. If you do however, unfortunately you will need to wait for me to patch the tool properly to support the new format.

**Comment by Barros1776** [comment]
it's working just fine. My team says thanks.

**Comment by OverlordZorn** [comment]
@soda3x being cacually a chad.

**Comment by soda3x** [comment]
`v0.9.0` will fully support the disableNavmeshStreaming parameter in compliance with Arma Reforger `v1.2`
