### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Bandesss** [soda3x/ArmaReforgerServerTool#62]
Hi I love your program but with the fix I get this error
https://prnt.sc/YC5C6iPxNY6Z
Thx for Help

**Comment by armijocj** [comment]
Hi, in the past I would get that too, found out it is a mod that didn't get updated and a new update just came out for he game. You will have to go threw each mod and see what one is giving you problem

**Comment by armijocj** [comment]
Sorry, looking at your picture again remove mode getOwnerVehicle

**Comment by Bandesss** [comment]
Thanks, I don't have the mod in it?

**Comment by soda3x** [comment]
Not related to the tool directly, this is likely a mod issue or Arma Reforger issue. Closing.
