### ISSUE TITLE
Mod Problem

### ISSUE THREAD

**Issue by sarteko** [soda3x/ArmaReforgerServerTool#7]
Hi, I have difficulty with mods, is it possible to know what is the path where to insert them? Thank you

**Comment by soda3x** [comment]
What exactly are you struggling with? Have a look [here](https://community.bistudio.com/wiki/Arma_Reforger:Server_Hosting) for detailed info about reforger server hosting.

**Comment by soda3x** [comment]
Going to close this now, open a new issue if you are still having issues.
