### ISSUE TITLE
[Feature] add -listScenarios as startup option

### ISSUE THREAD

**Issue by MildlyInterested** [soda3x/ArmaReforgerServerTool#8]
Useful to determine ID of custom scenarios. See here https://community.bistudio.com/wiki/Arma_Reforger:Startup_Parameters#listScenarios

**Comment by soda3x** [comment]
I did try this early on, it's a bit of a challenge to parse because of the way they format the response. I'll look into it again, it's probably improved (hopefully).

**Comment by soda3x** [comment]
Would you want it as a startup option or would you want the program to run that command and compile a list of the custom scenarios for your choosing in the GUI?

**Comment by MildlyInterested** [comment]
Thanks for the fast answer!
While a GUI solution would be ideal I think adding to the startup without parsing is enough. 
Just looking for a fast way to get the missions IDs and most of the console.log seems to be getting displayed directly in your tool anyway so don't see the need for parsing.

**Comment by soda3x** [comment]
How about I add the feature as a startup parameter for the time being as a short time solution, and I slowly get it as a GUI feature? Startup parameter would be quite easy to implement so I see no issue in doing that

**Comment by MildlyInterested** [comment]
Sounds great to me!
Thanks for you work.

**Comment by soda3x** [comment]
Hiya! I'm working on this now, but have run into a bit of a road block. Unfortunately the list scenario output is actually not stdout or stderr and they're the only outputs available to redirect. I'll continue to investigate, I've not given up hope yet. It is seriously annoying that the reforger server application is like this though....

**Comment by MildlyInterested** [comment]
Ah that also explains why I've not been seeing the whole log file directly in the gui and only parts of it.
I've got two devs from the reforger team in my arma unit, I'll forward your complaint to them, let's hope it does something :D

**Comment by soda3x** [comment]
Hey, did anything come of this?

**Comment by coldplain1** [comment]
Having a problem. Created installer, but installer doesn't create an Program exe, only a uninstall exe

**Comment by soda3x** [comment]
Hi @coldplain1, will respond in #9

**Comment by soda3x** [comment]
Resolved in `v0.7`
