### ISSUE TITLE
Installer not creating Program.exe

### ISSUE THREAD

**Issue by coldplain1** [soda3x/ArmaReforgerServerTool#9]
I finally figured out how to get the Dir compiled and was able to make installer. The installer makes the 6.0 folder and a Uninstaller.exe, but no ArmaReforgerServerTool.exe. Am I doing something wrong? Please advise. Thank you!

**Comment by soda3x** [comment]
Are you using the installer supplied in the latest release or are you compiling the installer with NSIS yourself?

**Comment by soda3x** [comment]
If the latter, does the build complete successfully and an `ArmaReforgerServerTool.exe` appears in the build directory?

**Comment by coldplain1** [comment]
I was not aware there was an installer. Could you direct me to it please?

**Comment by coldplain1** [comment]
ive3 been trying to compile it and create with MakeNSIS

**Comment by soda3x** [comment]
https://github.com/soda3x/ArmaReforgerServerTool/releases/tag/v0.5

**Comment by coldplain1** [comment]
thank you! you just saved me so much work.

**Comment by soda3x** [comment]
No worries, happy to help
