### ISSUE TITLE
Multiple mods in a list can be selected and moved at once.

### ISSUE THREAD

**Issue by benfleuty** [soda3x/ArmaReforgerServerTool#90]
It was asked in Discord if multiple mods could be selected and moved together.
[Link to message](https://discord.com/channels/1227418679520657418/1227419246754004993/1287406823787331697).

For example, if you have disabled mods `a` thru `z`, you can select `b c e r y` and click `>`. `b c e r y` would then be added to the enabled list.

**Comment by soda3x** [comment]
sounds like a good feature, looking forward to it :)

**Comment by Bandesss** [comment]
Hello everyone, is there anything new?

**Comment by benfleuty** [comment]
@Bandesss the work is complete and has been tested. It is currently available on our `dev` branch. @soda3x may have more information regarding the stable branch.

**Comment by Bandesss** [comment]
Thx for Answer👍

**Comment by soda3x** [comment]
Added in v0.9.1, thanks @benfleuty for that!
