### ISSUE TITLE
Version 0.9.1

### ISSUE THREAD

**Issue by NASYROV777** [soda3x/ArmaReforgerServerTool#98]
When adding any modification, the server does not start!

**Comment by soda3x** [comment]
Yep, this is fixed and will be deployed as a hotfix, thanks for raising this!

**Comment by soda3x** [comment]
Re-download version 0.9.1, it should now work. You will just need to install it over the top of your existing install :) Let me know if that works!

**Comment by NASYROV777** [comment]
Thanks for the quick response! I'll check when I get home. I will
definitely write to you

пт, 29 нояб. 2024 г., 12:49 Bradley Newman ***@***.***>:

**Comment by NASYROV777** [comment]
> Переустановите версию 0.9.1, теперь она должна работать. Вам просто нужно будет установить её поверх существующей версии :) Дайте мне знать, если это сработает!

[Super! You can play with your friends! Thanks for the correction!](https://translate.yandex.ru/)
